export const SUPPORTED_LANGUAGES = [
  { code: "en-US", name: "English (US)", flag: "🇺🇸" },
  { code: "en-GB", name: "English (UK)", flag: "🇬🇧" },
  { code: "hi-IN", name: "Hindi (India)", flag: "🇮🇳" },
  { code: "es-ES", name: "Spanish (Spain)", flag: "🇪🇸" },
  { code: "fr-FR", name: "French (France)", flag: "🇫🇷" },
  { code: "de-DE", name: "German (Germany)", flag: "🇩🇪" },
  { code: "ja-JP", name: "Japanese (Japan)", flag: "🇯🇵" },
  { code: "zh-CN", name: "Chinese (Mandarin)", flag: "🇨🇳" },
  { code: "pt-BR", name: "Portuguese (Brazil)", flag: "🇧🇷" },
  { code: "ar-SA", name: "Arabic (Saudi Arabia)", flag: "🇸🇦" },
];

export const INITIAL_PHRASES = [
  {
    id: "p-1",
    text: "Hello, nice to meet you!",
    category: "Greetings",
    emoji: "👋",
    favorite: true,
    quickAudio: true,
  },
  {
    id: "p-2",
    text: "I am deaf / hard of hearing. Please look at me when speaking.",
    category: "Communication",
    emoji: "🧏",
    favorite: true,
    quickAudio: true,
  },
  {
    id: "p-3",
    text: "Could you please speak a bit slower or write it down?",
    category: "Communication",
    emoji: "✍️",
    favorite: true,
    quickAudio: false,
  },
  {
    id: "p-4",
    text: "I need assistance, please help me.",
    category: "Emergency",
    emoji: "🚨",
    favorite: true,
    quickAudio: true,
  },
  {
    id: "p-5",
    text: "Where is the nearest restroom / exit?",
    category: "Everyday",
    emoji: "🚻",
    favorite: false,
    quickAudio: false,
  },
  {
    id: "p-6",
    text: "Thank you very much for your understanding!",
    category: "Greetings",
    emoji: "🙏",
    favorite: true,
    quickAudio: true,
  },
  {
    id: "p-7",
    text: "Can I have water with no ice, please?",
    category: "Food & Dining",
    emoji: "💧",
    favorite: false,
    quickAudio: false,
  },
  {
    id: "p-8",
    text: "I am using SignBridge to communicate with you.",
    category: "Communication",
    emoji: "🤟",
    favorite: true,
    quickAudio: true,
  },
  {
    id: "p-9",
    text: "Please call an ambulance / medical staff.",
    category: "Emergency",
    emoji: "🚑",
    favorite: false,
    quickAudio: true,
  },
  {
    id: "p-10",
    text: "What is the Wi-Fi password here?",
    category: "Everyday",
    emoji: "📶",
    favorite: false,
    quickAudio: false,
  },
];
